# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import items.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('file', models.CharField(max_length=450)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('0', 'Entregado'), ('1', 'En revision'), ('2', 'Finalizado')], default='0', max_length=1)),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='actual_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=450, upload_to=items.models.path_document),
        ),
        migrations.AddField(
            model_name='version',
            name='actual_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.File'),
        ),
    ]
